### ISSUE TITLE
UndefVarError: unpack not defined

### ISSUE THREAD

**Issue by onetonfoot** [MikeInnes/Flux.jl#14]
Hi, I get this error

UndefVarError: unpack not defined
 in makesession(::Flux.Unrolled) at /home/dom/.julia/v0.5/Flux/src/backend/tensorflow/recurrent.jl:13
 in tf(::Flux.Unrolled) at /home/dom/.julia/v0.5/Flux/src/backend/tensorflow/recurrent.jl:28
 in tf(::Flux.Unrolled, ::Vararg{Flux.Unrolled,N}) at /home/dom/.julia/v0.5/Flux/src/backend/backend.jl:10

when trying to run this section of code from the Char RNN example
```julia
model = Chain(
  Input(N),
  LSTM(N, 256),
  LSTM(256, 256),
  Affine(256, N),
  softmax)

m = tf(unroll(model, nunroll))

@time Flux.train!(m, Xs, Ys, η = 0.1, epoch = 1)
```

Thought it may be to do with a recent tensfor flow API  	[change](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) since I'm running TensorFlow version 1.0.1.  I tried to change unpack to unstack in recurrent.jl and graph.jl but it didn't seem to work.

**Comment by MikeInnes** [comment]
Can you show me the output of `Pkg.status()`? I can't reproduce this on Flux v0.1.1 with TensorFlow v0.5.1.

**Comment by onetonfoot** [comment]
Sorry this may have been an error with the TensorFlow.jl package, I had a half working version, it functioned but I didn't release it was failing ```Pkg.test()```. Having downgraded to TensorFlow  0.12.0 the issue is now resolved.
