### ISSUE TITLE
Unsupported model expression error on simple @net command

### ISSUE THREAD

**Issue by currymj** [MikeInnes/Flux.jl#39]
When trying to do run the very first piece of example code, `@net f(x) = x .* x`, I get a bewildering error. This is in Juno but the same thing happens in the regular Julia command line. `Pkg.test("Flux")` results in all tests passing.

```
> @net f(x) = x .* x
Unsupported model expression f(x) = begin  # console, line 1:
        x .* x
    end
 in include_string(::String, ::String) at loading.jl:441
 in include_string(::String, ::String) at sys.dylib:?
 in eval(::Module, ::Any) at boot.jl:234
 in eval(::Module, ::Any) at sys.dylib:?
 in (::Atom.##65#68)() at eval.jl:102
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:38
 in macro expansion at eval.jl:101 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60
```

Here's my Julia version:

```
  | | |_| | | | (_| |  |  Version 0.5.2 (2017-05-06 16:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0
```

**Comment by alha02** [comment]
I think the minimum required julia version is 0.6. Perhaps that is the issue?

**Comment by staticfloat** [comment]
This is happening because you're looking at the docs for the `master` branch of `Flux`, which is 0.6 only.  The 0.5-compatible docs are [here](http://mikeinnes.github.io/Flux.jl/v0.1.1/models/basics.html).

**Comment by MikeInnes** [comment]
Yup, we're in a slightly annoying transition period right now but soon 0.6 will have full support and all the best features.

I think you can do `f = @net x->x.*x` to get around this.

**Comment by currymj** [comment]
On 0.6-rc2, with Flux checked out to master, and MXNet installed, I still get the same error.

**Comment by MikeInnes** [comment]
Can you show your `Pkg.status()`? This certainly shouldn't be possible on master.

**Comment by currymj** [comment]
It appears you're right. I'm not sure what I forgot to do, but there appears to be no problem now. Thanks!
