### ISSUE TITLE
char-rnn example with MXNet backend

### ISSUE THREAD

**Issue by georgeblck** [MikeInnes/Flux.jl#8]
Thank you for this package, I like it a lot.
I was wondering how one would write the char-rnn example while using the MXNet backend.

This is the code using tf, which is pretty straightforward:
`m = tf(unroll(model, nunroll))`
The `mxnet()` function needs some additional arguments, which I don't understand in this example.

**Comment by MikeInnes** [comment]
Unfortunately this isn't possible right now, I'm still working on making the APIs for recurrence complete. But since you asked I can bump this up the priority list and try to get it working this week or so.

Just curious, is there a particular reason you want to use MXNet over TensorFlow?

**Comment by georgeblck** [comment]
Thank you for the quick answer; that would be terrific!
The main reason is, that MXNet is already built on the different machines (GPU & CPU) that I am using (which took a while). I am working on building TensorFlow on them, but it is not my strong suit.

**Comment by georgeblck** [comment]
Are there any updates on the MXNet backend and the LSTM example?

**Comment by MikeInnes** [comment]
This more-or-less works on the master branch but isn't quite ready for release. If you're willing to get your hands a bit dirty I can try to put some instructions together.

**Comment by MikeInnes** [comment]
I'm currently tagging a release which fixes this: https://github.com/JuliaLang/METADATA.jl/pull/9101
